# Global
variable "name" {
  type        = string
  description = "The name of the deployment."
  default     = "longhorn"
}

variable "namespace" {
  type        = string
  description = "The namespace of the deployment."
  default     = "longhorn-system"
}

variable "compartment" {
  type        = string
  description = "The compartment the ressource is deployed with."
}

# Helm
variable "helm_chart_version" {
  type    = string
  default = "1.4.2"
}

# Backup - AWS
variable "aws_access_key_id" {
  type        = string
  default     = ""
  description = "The AWS_ACCESS_KEY_ID for the S3 Backup Bucket"
}

variable "aws_secret_access_key" {
  type        = string
  default     = ""
  description = "The AWS_SECRET_ACCESS_KEY for the S3 Backup Bucket."
}

# Ingress
variable "ingress_enabled" {
  type        = bool
  default     = false
  description = "Exposes the Longhorn UI"
}

variable "ingress_dns" {
  type        = string
  description = "The domain name where longhorn should be reachable."
}

variable "ingress_type" {
  type        = string
  description = "The ingress type. Can be either 'traefik', 'istio' or 'none'"
  default     = "none"
}

# Certificate
variable "issuer_name" {
  type        = string
  description = "The certifictae issuer name."
  default     = "cloudflare-letsencrypt-staging"
}

variable "issuer_type" {
  type        = string
  description = "The certifictae issuer type."
  default     = "ClusterIssuer"
}

# Gatekeeper
variable "gatekeeper_client_id" {
  type        = string
  description = "The client ID of the longhorn client."
}

variable "gatekeeper_client_secret" {
  type        = string
  description = "The client secret of the longhorn client."
}

variable "gatekeeper_encryption_key" {
  type        = string
  description = "The encryption key. If unset, the key will be generated by terraform."
}

variable "gatekeeper_redirection_url" {
  type        = string
  description = "The url where longhorn should be reachable."
}

variable "gatekeeper_discovery_url" {
  type        = string
  description = "The url of the keycloak iam provider"
}
